#!/usr/bin/env bash
# Fetch the production QuestDB admin password from the cluster into a git-ignored .env.
# Never prints the password. Refuses to run against an unexpected kube context.
#
# usage: scripts/fetch-creds.sh [--force] [--context NAME] [--env-file PATH]
set -euo pipefail
set +x

EXPECTED_CONTEXT="cauchy-cnvrg-cauchy-clstr"
ENV_FILE=".env"
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    --context) EXPECTED_CONTEXT="$2"; shift 2 ;;
    --env-file) ENV_FILE="$2"; shift 2 ;;
    -h|--help) sed -n '2,6p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

command -v kubectl >/dev/null || { echo "kubectl not found; paste the password into $ENV_FILE by hand (see .env.example)" >&2; exit 1; }

CURRENT_CONTEXT="$(kubectl config current-context 2>/dev/null || true)"
if [[ "$CURRENT_CONTEXT" != "$EXPECTED_CONTEXT" ]]; then
  echo "refusing: current kube context is '$CURRENT_CONTEXT', expected '$EXPECTED_CONTEXT' (override with --context)" >&2
  exit 1
fi

if [[ -e "$ENV_FILE" && $FORCE -ne 1 ]]; then
  echo "refusing: $ENV_FILE already exists (use --force to overwrite)" >&2
  exit 1
fi

PASSWORD="$(kubectl get secret -n questdb questdb-secrets -o jsonpath='{.data.DB_PASS}' | base64 -d)"
if [[ -z "$PASSWORD" ]]; then
  echo "secret questdb-secrets/DB_PASS came back empty" >&2
  exit 1
fi

umask 077
TMP="$(mktemp "${ENV_FILE}.XXXXXX")"
{
  echo "# generated by scripts/fetch-creds.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ); git-ignored"
  echo "QDB_HOST=127.0.0.1"
  echo "QDB_PORT=19000"
  echo "QDB_USER=admin"
  echo "QDB_PASSWORD=$PASSWORD"
} > "$TMP"
chmod 600 "$TMP"
mv "$TMP" "$ENV_FILE"
unset PASSWORD

echo "wrote QDB_PASSWORD ($(grep -c '^QDB_PASSWORD=' "$ENV_FILE" >/dev/null && sed -n 's/^QDB_PASSWORD=//p' "$ENV_FILE" | awk '{print length($0)}') chars) to $ENV_FILE"
